### ISSUE TITLE
New build numbers not being uploaded?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/primesieve-feedstock#4]
Even though the build number has gone up twice, it seems that it only builds everything as if it were build number `0` and uploads it. Need to figure out what is going wrong here and how to fix it.

**Comment by jakirkham** [comment]
cc @pelson

**Comment by jakirkham** [comment]
NVM this was a terribly foolish user error. Fortunately, it is easily corrected.

**Comment by pelson** [comment]
Yay. That was going to be a horrible bug somewhere which could have taken ages to find! 😄 
Glad it was a [simple repetition of the build section](https://github.com/conda-forge/primesieve-feedstock/commit/b083f1044bc7f1cb7d7cbd48b214136ab1d4a249) in the end! 🎉
